Initial Handlebars Template and Scripts
Added template.js to turn FatJSON into stuff on the webpage. Some other
.js needs to make the FatJSON. The template has some placeholder items
until I can play around with what the read FatJSON will look like.
The testing.js is broken. It gives this error
"/var/www/html/testing.js:3
champs = [
^
SyntaxError: Unexpected token =
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:935:3"
But I should be able to just pull all the data out myself to make a
testing.json.